# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
publish = "userguide/public"
command = "npm run docs-install && npm run build:preview"

[build.environment]
GO_VERSION = "1.19.5"
HUGO_THEME = "repo"

[context.production]
command = "npm run docs-install && npm run build:production"

#[context.deploy-preview]
#command = "npm install -D autoprefixer && npm install -D postcss-cli && cd userguide && hugo --minify --themesDir ../../ --baseURL $DEPLOY_PRIME_URL"
#[[context.deploy-preview.plugins]]
#package = "netlify-plugin-checklinks"

#  [context.deploy-preview.plugins.inputs]
#  skipPatterns = [ "/_print" ]
#  followSourceMaps = false
#  checkExternal = false

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  skipPatterns = [ "/_print" ]
  followSourceMaps = false
  checkExternal = false