# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
base = "userguide"
command = "hugo --themesDir ../.."

[build.environment]
NODE_VERSION = "19.6.1"
HUGO_VERSION = "0.110.0"
GO_VERSION = "1.20.1"
HUGO_THEME = "repo"

[context.production]
command = "hugo --themesDir ../.."
